{% set version = "0.11.1" %}

package:
  name: colt5-attention
  version: {{ version }}

source:
  url: https://github.com/lucidrains/colt5-attention/archive/{{ version }}.tar.gz
  sha256: 597f1e4af5b9006d8969d73905ea03fcc55945cfb0ab7d3d722fd05fff6322f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - einops >=0.8.0
    - local-attention >=1.8.6
    - packaging
    - pytorch >=1.10

test:
  commands:
    - pip check
  imports:
    - colt5_attention
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/lucidrains/CoLT5-attention
  license: MIT
  license_file: LICENSE
  summary: Implementation of the conditionally routed attention in the CoLT5 architecture, in Pytorch

extra:
  recipe-maintainers:
    - danielnachun
